import {
  AdminProduct,
  AdminOrder,
  AdminUser,
  AdminCategory,
  AdminOffer,
  AdminSalesPoint,
  AdminSupportTicket,
  AdminBanner,
  AdminFlashDeal,
} from './types';

export const INITIAL_CATEGORIES: AdminCategory[] = [
  {
    id: 'chicken',
    name: 'Chicken',
    iconName: 'Beef',
    image: '/src/assets/images/cat_chicken_1790504356265.jpg',
    productCount: 6,
  },
  {
    id: 'mutton',
    name: 'Mutton',
    iconName: 'Flame',
    image: '/src/assets/images/cat_mutton_1790504374485.jpg',
    productCount: 5,
  },
  {
    id: 'fish',
    name: 'Fish',
    iconName: 'Utensils',
    image: '/src/assets/images/cat_fish_1790504389877.jpg',
    productCount: 5,
  },
  {
    id: 'eggs',
    name: 'Eggs',
    iconName: 'Cookie',
    image: '/src/assets/images/cat_eggs_1790504403080.jpg',
    productCount: 4,
  },
  {
    id: 'ready-to-cook',
    name: 'Ready to Cook',
    iconName: 'Flame',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    productCount: 5,
  },
  {
    id: 'special-cuts',
    name: 'Special Cuts',
    iconName: 'Utensils',
    image: '/src/assets/images/cat_special_cuts_1790507586236.jpg',
    productCount: 4,
  },
  {
    id: 'prawns',
    name: 'Prawns & Seafood',
    iconName: 'Utensils',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    productCount: 4,
  },
  {
    id: 'cold-cuts',
    name: 'Cold Cuts',
    iconName: 'Sandwich',
    image: '/src/assets/images/cat_cold_cuts_1790508827963.jpg',
    productCount: 4,
  },
  {
    id: 'marinades',
    name: 'Marinades & Kebabs',
    iconName: 'Flame',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    productCount: 4,
  },
];

export const INITIAL_PRODUCTS: AdminProduct[] = [
  // ================= Chicken =================
  {
    id: 'ch-1',
    name: 'Fresh Chicken Curry Cut',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 420,
    originalPrice: 465,
    stockQuantity: 45,
    unit: '1 KG',
    description: 'Fresh, juicy bone-in cuts of farm-reared healthy chicken. Washed with purified water and hygienically packed for home gravies and curries.',
    image: '/src/assets/images/chicken_curry_cut_wide_1790508282856.jpg',
    isActive: true,
    createdAt: 'Apr 12, 2025',
    salesCount: 1240,
  },
  {
    id: 'ch-2',
    name: 'Fresh Chicken Breast Boneless',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 480,
    originalPrice: 510,
    stockQuantity: 38,
    unit: '1 KG',
    description: 'High-protein tender skinless and boneless chicken breast fillets. Perfect for fitness diets, stir-fries, and gourmet steaks.',
    image: '/src/assets/images/cat_chicken_1790504356265.jpg',
    isActive: true,
    createdAt: 'Apr 14, 2025',
    salesCount: 820,
  },
  {
    id: 'ch-3',
    name: 'Tender Chicken Drumsticks',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 390,
    originalPrice: 425,
    stockQuantity: 52,
    unit: '1 KG',
    description: 'Succulent and meaty chicken lower leg drumsticks, trimmed and ready for slow roasting, tandoor grills, and aromatic biryanis.',
    image: '/src/assets/images/offer_chicken_card_1790507696774.jpg',
    isActive: true,
    createdAt: 'Apr 15, 2025',
    salesCount: 640,
  },
  {
    id: 'ch-4',
    name: 'Fresh Chicken Wings (Skin-On)',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 340,
    originalPrice: 385,
    stockQuantity: 40,
    unit: '1 KG',
    description: 'Crispy skin-on fresh chicken wingettes and drumettes. Ideal for hot buffalo wings, BBQ platters, and air fryer snacks.',
    image: '/src/assets/images/chicken_curry_cut_wide_1790508282856.jpg',
    isActive: true,
    createdAt: 'Apr 16, 2025',
    salesCount: 410,
  },
  {
    id: 'ch-5',
    name: 'Minced Chicken Keema',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 460,
    originalPrice: 490,
    stockQuantity: 28,
    unit: '1 KG',
    description: 'Finely minced premium chicken breast & thigh meat. Ideal for chicken patties, kebabs, samosas, and keema matar.',
    image: '/src/assets/images/cat_chicken_1790504356265.jpg',
    isActive: true,
    createdAt: 'Apr 18, 2025',
    salesCount: 390,
  },
  {
    id: 'ch-6',
    name: 'Boneless Chicken Thighs',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 510,
    originalPrice: 540,
    stockQuantity: 34,
    unit: '1 KG',
    description: 'Juicy, flavorful boneless dark meat chicken thighs with natural fats that stay tender and moist when grilled or curried.',
    image: '/src/assets/images/curry_cut_chicken_1790507633294.jpg',
    isActive: true,
    createdAt: 'Apr 20, 2025',
    salesCount: 510,
  },

  // ================= Mutton =================
  {
    id: 'mu-1',
    name: 'Fresh Mutton Boneless',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 680,
    originalPrice: 720,
    stockQuantity: 25,
    unit: '1 KG',
    description: '100% Halal certified, hand-trimmed tender goat meat cubes without any bones. Absorbs spices deeply for royal mutton curries.',
    image: '/src/assets/images/mutton_boneless_wide_1790508301717.jpg',
    isActive: true,
    createdAt: 'Apr 12, 2025',
    salesCount: 856,
  },
  {
    id: 'mu-2',
    name: 'Rich Mutton Curry Cut (Bone-In)',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 620,
    originalPrice: 690,
    stockQuantity: 32,
    unit: '1 KG',
    description: 'Even mix of bone-in and tender mutton cuts including ribs, shoulder, and shank for deeply flavorful, rich traditional gravy.',
    image: '/src/assets/images/cat_mutton_1790504374485.jpg',
    isActive: true,
    createdAt: 'Apr 14, 2025',
    salesCount: 940,
  },
  {
    id: 'mu-3',
    name: 'Fresh Mutton Chops & Ribs',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 740,
    originalPrice: 780,
    stockQuantity: 20,
    unit: '1 KG',
    description: 'Succulent lamb and mutton rib chops cut with bone-in precision for smoky pan searing, BBQ grilling, or masala chops.',
    image: '/src/assets/images/offer_mutton_card_1790507713635.jpg',
    isActive: true,
    createdAt: 'Apr 17, 2025',
    salesCount: 380,
  },
  {
    id: 'mu-4',
    name: 'Fine Mutton Keema (Minced)',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 710,
    originalPrice: 750,
    stockQuantity: 22,
    unit: '1 KG',
    description: 'Pure goat meat twice minced on hygienic stainless steel machines for smooth texture. Perfect for Lucknowi seekh and keema parathas.',
    image: '/src/assets/images/mutton_boneless_cubes_1790507651522.jpg',
    isActive: true,
    createdAt: 'Apr 19, 2025',
    salesCount: 420,
  },
  {
    id: 'mu-5',
    name: 'Tender Goat Biryani Cut',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 650,
    originalPrice: 690,
    stockQuantity: 30,
    unit: '1 KG',
    description: 'Specially chosen chunky cuts with soft marrow bones that infuse authentic aroma into Dum Biryani layers.',
    image: '/src/assets/images/mutton_boneless_wide_1790508301717.jpg',
    isActive: true,
    createdAt: 'Apr 21, 2025',
    salesCount: 610,
  },

  // ================= Fish =================
  {
    id: 'fi-1',
    name: 'Fresh Rohu Fish (Cleaned)',
    category: 'Fish',
    categoryId: 'fish',
    price: 260,
    originalPrice: 285,
    stockQuantity: 40,
    unit: '1 KG',
    description: 'Fresh freshwater Rohu cut into Bengali curry steaks. Thoroughly descaled, gutted, and washed with ice-chill freshness guaranteed.',
    image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
    isActive: true,
    createdAt: 'Apr 13, 2025',
    salesCount: 632,
  },
  {
    id: 'fi-2',
    name: 'White Pomfret (Cleaned & Gutted)',
    category: 'Fish',
    categoryId: 'fish',
    price: 790,
    originalPrice: 830,
    stockQuantity: 18,
    unit: '1 KG',
    description: 'Premium sea-caught White Pomfret with delicate tender white meat and buttery sweet flavor. Cleaned whole and slit-ready for tawa fry.',
    image: '/src/assets/images/cat_fish_1790504389877.jpg',
    isActive: true,
    createdAt: 'Apr 15, 2025',
    salesCount: 512,
  },
  {
    id: 'fi-3',
    name: 'Surmai Steaks (King Fish)',
    category: 'Fish',
    categoryId: 'fish',
    price: 850,
    originalPrice: 890,
    stockQuantity: 15,
    unit: '1 KG',
    description: 'Thick, firm circular King Fish slices with minimal bones and mild ocean flavor. The ultimate favorite for coastal fish fry and curries.',
    image: '/src/assets/images/product_rohu_fish_1790507600370.jpg',
    isActive: true,
    createdAt: 'Apr 17, 2025',
    salesCount: 340,
  },
  {
    id: 'fi-4',
    name: 'Fresh Catla Bengalee Cut',
    category: 'Fish',
    categoryId: 'fish',
    price: 280,
    originalPrice: 310,
    stockQuantity: 35,
    unit: '1 KG',
    description: 'Sweet freshwater Catla fish slices with head & tail pieces included for authentic Macher Jhol preparations.',
    image: '/src/assets/images/cat_fish_1790504389877.jpg',
    isActive: true,
    createdAt: 'Apr 19, 2025',
    salesCount: 430,
  },
  {
    id: 'fi-5',
    name: 'Boneless Basa Fish Fillets',
    category: 'Fish',
    categoryId: 'fish',
    price: 420,
    originalPrice: 450,
    stockQuantity: 26,
    unit: '1 KG',
    description: 'Soft, delicate boneless river basa fillets with no fishy smell. Excellent for batter fish & chips, pan searing, and finger food.',
    image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
    isActive: true,
    createdAt: 'Apr 22, 2025',
    salesCount: 290,
  },

  // ================= Eggs =================
  {
    id: 'eg-1',
    name: 'Classic White Farm Eggs (Pack of 30)',
    category: 'Eggs',
    categoryId: 'eggs',
    price: 210,
    originalPrice: 245,
    stockQuantity: 65,
    unit: 'Pack of 30',
    description: 'Fresh farm eggs with bright yolks, packed directly from hygienic poultry farms with high protein content and zero antibiotics.',
    image: '/src/assets/images/cat_eggs_1790504403080.jpg',
    isActive: true,
    createdAt: 'Apr 10, 2025',
    salesCount: 1800,
  },
  {
    id: 'eg-2',
    name: 'Organic Brown Eggs (Pack of 12)',
    category: 'Eggs',
    categoryId: 'eggs',
    price: 140,
    originalPrice: 155,
    stockQuantity: 48,
    unit: 'Pack of 12',
    description: 'Nutrient-rich brown shelled eggs from free-roaming hens fed on natural grains and greens.',
    image: '/src/assets/images/cat_eggs_1790504403080.jpg',
    isActive: true,
    createdAt: 'Apr 13, 2025',
    salesCount: 890,
  },
  {
    id: 'eg-3',
    name: 'Free Range Country Eggs (Pack of 6)',
    category: 'Eggs',
    categoryId: 'eggs',
    price: 95,
    originalPrice: 110,
    stockQuantity: 50,
    unit: 'Pack of 6',
    description: 'Desi country chicken eggs enriched with essential Omega-3 fatty acids and golden deep yolks.',
    image: '/src/assets/images/cat_eggs_1790504403080.jpg',
    isActive: true,
    createdAt: 'Apr 15, 2025',
    salesCount: 540,
  },
  {
    id: 'eg-4',
    name: 'Fresh Quail Eggs (Pack of 24)',
    category: 'Eggs',
    categoryId: 'eggs',
    price: 160,
    originalPrice: 180,
    stockQuantity: 30,
    unit: 'Pack of 24',
    description: 'Bite-sized delicacy eggs loaded with iron, antioxidants, and vitamins. Ideal for gourmet salads and snacks.',
    image: '/src/assets/images/cat_eggs_1790504403080.jpg',
    isActive: true,
    createdAt: 'Apr 18, 2025',
    salesCount: 210,
  },

  // ================= Ready to Cook =================
  {
    id: 'rc-1',
    name: 'Chicken Malai Tikka (Marinated)',
    category: 'Ready to Cook',
    categoryId: 'ready-to-cook',
    price: 320,
    originalPrice: 355,
    stockQuantity: 35,
    unit: '400G',
    description: 'Tender chicken boneless chunks infused with rich cashew paste, cardamom, fresh cream, and mild green chilies. Ready to pan grill in 8 mins.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 11, 2025',
    salesCount: 980,
  },
  {
    id: 'rc-2',
    name: 'Spicy Mutton Seekh Kebab (4 Pcs)',
    category: 'Ready to Cook',
    categoryId: 'ready-to-cook',
    price: 360,
    originalPrice: 380,
    stockQuantity: 28,
    unit: 'Pack of 4',
    description: 'Traditional minced mutton kebabs blended with ginger, mint, cilantro, and royal kebab spices. Pre-skewered for quick heating.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 13, 2025',
    salesCount: 810,
  },
  {
    id: 'rc-3',
    name: 'Amritsari Fish Fry Cut',
    category: 'Ready to Cook',
    categoryId: 'ready-to-cook',
    price: 380,
    originalPrice: 410,
    stockQuantity: 22,
    unit: '500G',
    description: 'Fish fillet strips marinated in authentic Punjabi ajwain (carom), gram flour, yellow chili, and lemon batter.',
    image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
    isActive: true,
    createdAt: 'Apr 16, 2025',
    salesCount: 430,
  },
  {
    id: 'rc-4',
    name: 'Peri Peri Chicken Wings (Raw & Spiced)',
    category: 'Ready to Cook',
    categoryId: 'ready-to-cook',
    price: 290,
    originalPrice: 315,
    stockQuantity: 36,
    unit: '450G',
    description: 'Juicy wings coated in zesty African bird eye chili peri-peri rub. Bake, grill, or fry for instant snacking.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 19, 2025',
    salesCount: 640,
  },
  {
    id: 'rc-5',
    name: 'Tandoori Chicken Whole Leg (2 Pcs)',
    category: 'Ready to Cook',
    categoryId: 'ready-to-cook',
    price: 340,
    originalPrice: 370,
    stockQuantity: 30,
    unit: 'Pack of 2',
    description: 'Whole chicken leg cuts deeply scored and marinated in Kashmiri red chili, hung curd, and roasted tandoori spices.',
    image: '/src/assets/images/cat_chicken_1790504356265.jpg',
    isActive: true,
    createdAt: 'Apr 22, 2025',
    salesCount: 530,
  },

  // ================= Special Cuts =================
  {
    id: 'sc-1',
    name: 'Prime Ribeye Steak Cut',
    category: 'Special Cuts',
    categoryId: 'special-cuts',
    price: 890,
    originalPrice: 990,
    stockQuantity: 16,
    unit: '1 KG',
    description: 'Premium quality marbled cuts with center eye of fat that renders into melt-in-the-mouth tenderness upon high heat pan-searing.',
    image: '/src/assets/images/cat_special_cuts_1790507586236.jpg',
    isActive: true,
    createdAt: 'Apr 12, 2025',
    salesCount: 620,
  },
  {
    id: 'sc-2',
    name: 'Tender Lamb Shank (Osso Buco Cut)',
    category: 'Special Cuts',
    categoryId: 'special-cuts',
    price: 950,
    originalPrice: 1020,
    stockQuantity: 14,
    unit: '1 KG',
    description: 'Slow-cooking cut containing rich collagen and bone marrow that creates luxurious velvety sauce and braised lamb.',
    image: '/src/assets/images/hero_banner_meat_1790507616083.jpg',
    isActive: true,
    createdAt: 'Apr 15, 2025',
    salesCount: 390,
  },
  {
    id: 'sc-3',
    name: 'Gourmet French Lamb Chops',
    category: 'Special Cuts',
    categoryId: 'special-cuts',
    price: 1100,
    originalPrice: 1180,
    stockQuantity: 12,
    unit: '1 KG',
    description: 'Artisanal frenched rib chops with bone scraped clean for fine dining presentation and restaurant-grade dinner parties.',
    image: '/src/assets/images/cat_special_cuts_1790507586236.jpg',
    isActive: true,
    createdAt: 'Apr 18, 2025',
    salesCount: 410,
  },
  {
    id: 'sc-4',
    name: 'Chicken Breast Supreme (Skin-On)',
    category: 'Special Cuts',
    categoryId: 'special-cuts',
    price: 490,
    originalPrice: 530,
    stockQuantity: 24,
    unit: '1 KG',
    description: 'Single breast fillet with wing bone attached and golden skin intact for maximum moisture retention during oven roasting.',
    image: '/src/assets/images/cat_chicken_1790504356265.jpg',
    isActive: true,
    createdAt: 'Apr 21, 2025',
    salesCount: 280,
  },

  // ================= Prawns & Seafood =================
  {
    id: 'pr-1',
    name: 'Fresh Jumbo Tiger Prawns',
    category: 'Prawns & Seafood',
    categoryId: 'prawns',
    price: 750,
    originalPrice: 830,
    stockQuantity: 20,
    unit: '500G',
    description: 'Large sized sea-caught tiger prawns, head-on or cleaned on demand. Firm, sweet flesh ideal for garlic butter prawns and curries.',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    isActive: true,
    createdAt: 'Apr 11, 2025',
    salesCount: 810,
  },
  {
    id: 'pr-2',
    name: 'Cleaned Medium White Prawns',
    category: 'Prawns & Seafood',
    categoryId: 'prawns',
    price: 520,
    originalPrice: 560,
    stockQuantity: 25,
    unit: '500G',
    description: 'Fully peeled and deveined medium white prawns with tail on for quick stir-fry, pasta, and coastal prawn masala.',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    isActive: true,
    createdAt: 'Apr 14, 2025',
    salesCount: 520,
  },
  {
    id: 'pr-3',
    name: 'Fresh Crab Meat',
    category: 'Prawns & Seafood',
    categoryId: 'prawns',
    price: 640,
    originalPrice: 690,
    stockQuantity: 15,
    unit: '400G',
    description: 'Delicate sweet white crab meat extracted hygienically from fresh mud crabs. Perfect for soups, cutlets, and crab cakes.',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    isActive: true,
    createdAt: 'Apr 17, 2025',
    salesCount: 310,
  },
  {
    id: 'pr-4',
    name: 'Tender Squid Rings (Cleaned)',
    category: 'Prawns & Seafood',
    categoryId: 'prawns',
    price: 480,
    originalPrice: 520,
    stockQuantity: 18,
    unit: '400G',
    description: 'Cleaned calamari squid tubes cut into uniform rings. Tender and springy when quick flash-fried or tossed with chili garlic sauce.',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    isActive: true,
    createdAt: 'Apr 20, 2025',
    salesCount: 190,
  },

  // ================= Cold Cuts =================
  {
    id: 'cc-1',
    name: 'Chicken Smoked Salami (Sliced)',
    category: 'Cold Cuts',
    categoryId: 'cold-cuts',
    price: 190,
    originalPrice: 215,
    stockQuantity: 45,
    unit: '250G',
    description: 'Naturally hardwood-smoked fine chicken salami with black peppercorns. Ready to eat in sandwiches, pizzas, and charcuterie boards.',
    image: '/src/assets/images/cat_cold_cuts_1790508827963.jpg',
    isActive: true,
    createdAt: 'Apr 10, 2025',
    salesCount: 490,
  },
  {
    id: 'cc-2',
    name: 'Gourmet Chicken Frankfurters',
    category: 'Cold Cuts',
    categoryId: 'cold-cuts',
    price: 220,
    originalPrice: 240,
    stockQuantity: 35,
    unit: '300G',
    description: 'Juicy, seasoned European-style chicken hot dog sausages. Pre-cooked and ready to boil, pan grill, or steam.',
    image: '/src/assets/images/cat_cold_cuts_1790508827963.jpg',
    isActive: true,
    createdAt: 'Apr 13, 2025',
    salesCount: 380,
  },
  {
    id: 'cc-3',
    name: 'Spicy Chicken Pepperoni Slices',
    category: 'Cold Cuts',
    categoryId: 'cold-cuts',
    price: 240,
    originalPrice: 260,
    stockQuantity: 30,
    unit: '200G',
    description: 'Cured and dried zesty chicken pepperoni seasoned with paprika and chili for home-baked artisanal pizzas.',
    image: '/src/assets/images/cat_cold_cuts_1790508827963.jpg',
    isActive: true,
    createdAt: 'Apr 16, 2025',
    salesCount: 410,
  },
  {
    id: 'cc-4',
    name: 'Smoked Chicken Ham Loaf',
    category: 'Cold Cuts',
    categoryId: 'cold-cuts',
    price: 230,
    originalPrice: 250,
    stockQuantity: 28,
    unit: '250G',
    description: 'Lean cured whole chicken breast ham, gently spiced and cooked for breakfast toast and club sandwiches.',
    image: '/src/assets/images/cat_cold_cuts_1790508827963.jpg',
    isActive: true,
    createdAt: 'Apr 19, 2025',
    salesCount: 260,
  },

  // ================= Marinades =================
  {
    id: 'mr-1',
    name: 'Haryali Chicken Kebab Cut',
    category: 'Marinades & Kebabs',
    categoryId: 'marinades',
    price: 330,
    originalPrice: 360,
    stockQuantity: 32,
    unit: '450G',
    description: 'Boneless chicken cubes coated in vibrant green marinade of fresh garden mint, coriander leaves, green chili, and lemon juice.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 11, 2025',
    salesCount: 560,
  },
  {
    id: 'mr-2',
    name: 'Melt-in-Mouth Galouti Kebab (6 Pcs)',
    category: 'Marinades & Kebabs',
    categoryId: 'marinades',
    price: 380,
    originalPrice: 410,
    stockQuantity: 24,
    unit: 'Pack of 6',
    description: 'Awadhi royal recipe of ultra-smooth smoked minced meat with 16 royal spices and rose water. Pan fry on low heat with desi ghee.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 14, 2025',
    salesCount: 720,
  },
  {
    id: 'mr-3',
    name: 'Mustard Kasundi Fish Tikka',
    category: 'Marinades & Kebabs',
    categoryId: 'marinades',
    price: 410,
    originalPrice: 440,
    stockQuantity: 20,
    unit: '400G',
    description: 'Basa boneless chunks infused with pungent Bengal Kasundi mustard, mustard oil, turmeric, and green chilies.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 17, 2025',
    salesCount: 310,
  },
  {
    id: 'mr-4',
    name: 'Afghani Chicken Shashlik Skewers',
    category: 'Marinades & Kebabs',
    categoryId: 'marinades',
    price: 350,
    originalPrice: 390,
    stockQuantity: 28,
    unit: '450G',
    description: 'Mildly spiced creamy chicken skewers layered with crunchy bell peppers and onions, ready for stove grill or oven.',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    isActive: true,
    createdAt: 'Apr 20, 2025',
    salesCount: 440,
  },
];

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: 'ord_1024',
    orderNumber: '#ORD1024',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    deliveryAddress: 'Flat 402, Royal Palms, Sector 10, Noida, UP - 201301',
    date: 'Apr 28, 2025',
    time: '10:24 AM',
    status: 'Preparing',
    paymentMethod: 'Online / UPI',
    items: [
      {
        productId: 'ch-1',
        name: 'Fresh Chicken Curry Cut',
        price: 420,
        quantity: 1,
        unit: '1 KG',
        image: '/src/assets/images/chicken_curry_cut_wide_1790508282856.jpg',
      },
      {
        productId: 'eg-1',
        name: 'Classic White Farm Eggs (Pack of 30)',
        price: 210,
        quantity: 1,
        unit: 'Pack of 30',
        image: '/src/assets/images/cat_eggs_1790504403080.jpg',
      },
    ],
    subTotal: 630,
    deliveryFee: 40,
    total: 670,
  },
  {
    id: 'ord_1023',
    orderNumber: '#ORD1023',
    customerName: 'Ayesha Khan',
    customerPhone: '+91 98123 45678',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    deliveryAddress: 'House 14B, Green Park Extension, New Delhi - 110016',
    date: 'Apr 28, 2025',
    time: '09:45 AM',
    status: 'On the Way',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'mu-1',
        name: 'Fresh Mutton Boneless',
        price: 680,
        quantity: 1,
        unit: '1 KG',
        image: '/src/assets/images/mutton_boneless_wide_1790508301717.jpg',
      },
      {
        productId: 'rc-1',
        name: 'Chicken Malai Tikka (Marinated)',
        price: 320,
        quantity: 1,
        unit: '400G',
        image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
      },
    ],
    subTotal: 1000,
    deliveryFee: 0,
    total: 1000,
  },
  {
    id: 'ord_1022',
    orderNumber: '#ORD1022',
    customerName: 'Vikram Mehta',
    customerPhone: '+91 99887 76655',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    deliveryAddress: 'Villa 88, Palm Meadows, Whitefield, Bangalore - 560066',
    date: 'Apr 28, 2025',
    time: '08:12 AM',
    status: 'Delivered',
    paymentMethod: 'Online / UPI',
    items: [
      {
        productId: 'fi-1',
        name: 'Fresh Rohu Fish (Cleaned)',
        price: 260,
        quantity: 2,
        unit: '1 KG',
        image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
      },
      {
        productId: 'pr-1',
        name: 'Fresh Jumbo Tiger Prawns',
        price: 750,
        quantity: 1,
        unit: '500G',
        image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
      },
    ],
    subTotal: 1270,
    deliveryFee: 0,
    total: 1270,
  },
  {
    id: 'ord_1021',
    orderNumber: '#ORD1021',
    customerName: 'Pooja Verma',
    customerPhone: '+91 97654 32109',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    deliveryAddress: 'B-201, Express Greens, Sector 1, Greater Noida - 201306',
    date: 'Apr 27, 2025',
    time: '07:30 PM',
    status: 'Cancelled',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'ch-3',
        name: 'Tender Chicken Drumsticks',
        price: 390,
        quantity: 1,
        unit: '1 KG',
        image: '/src/assets/images/offer_chicken_card_1790507696774.jpg',
      },
    ],
    subTotal: 390,
    deliveryFee: 40,
    total: 430,
  },
  {
    id: 'ord_1020',
    orderNumber: '#ORD1020',
    customerName: 'Amit Trivedi',
    customerPhone: '+91 98450 12345',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    deliveryAddress: 'Tower 4, Flat 1204, Cyber City, Gurugram - 122002',
    date: 'Apr 27, 2025',
    time: '11:15 AM',
    status: 'Pending',
    paymentMethod: 'Online / UPI',
    items: [
      {
        productId: 'mu-2',
        name: 'Rich Mutton Curry Cut (Bone-In)',
        price: 620,
        quantity: 2,
        unit: '1 KG',
        image: '/src/assets/images/cat_mutton_1790504374485.jpg',
      },
    ],
    subTotal: 1240,
    deliveryFee: 40,
    total: 1280,
  },
];

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'usr_1',
    name: 'Rahul Sharma',
    phone: '+91 98765 43210',
    email: 'rahul.sharma@example.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    totalOrders: 14,
    totalSpent: 8420,
    joinedDate: 'Jan 15, 2025',
  },
  {
    id: 'usr_2',
    name: 'Ayesha Khan',
    phone: '+91 98123 45678',
    email: 'ayesha.k@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    totalOrders: 9,
    totalSpent: 6250,
    joinedDate: 'Feb 02, 2025',
  },
  {
    id: 'usr_3',
    name: 'Vikram Mehta',
    phone: '+91 99887 76655',
    email: 'vikram.mehta@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    totalOrders: 22,
    totalSpent: 14800,
    joinedDate: 'Nov 12, 2024',
  },
  {
    id: 'usr_4',
    name: 'Fatima Noor',
    phone: '+91 97654 32109',
    email: 'fatima.n@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Blocked',
    totalOrders: 2,
    totalSpent: 860,
    joinedDate: 'Mar 10, 2025',
  },
  {
    id: 'usr_5',
    name: 'Amit Trivedi',
    phone: '+91 98450 12345',
    email: 'amit.trivedi@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    totalOrders: 18,
    totalSpent: 11950,
    joinedDate: 'Dec 05, 2024',
  },
  {
    id: 'usr_6',
    name: 'Pooja Verma',
    phone: '+91 98990 66778',
    email: 'pooja.verma@example.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    totalOrders: 7,
    totalSpent: 3890,
    joinedDate: 'Feb 20, 2025',
  },
];

export const INITIAL_OFFERS: AdminOffer[] = [
  {
    id: 'off_1',
    title: 'Flat ₹100 OFF on Fresh Mutton Cuts',
    description: 'Use code MUTTON100 on orders above ₹600.',
    couponCode: 'MUTTON100',
    discountType: 'flat',
    discountValue: '₹100',
    validTill: '30 May, 2025',
    image: '/src/assets/images/offer_mutton_card_1790507713635.jpg',
    isActive: true,
  },
  {
    id: 'off_2',
    title: '15% OFF on Fresh Chicken Curry Cut',
    description: 'Get 15% instant discount on prime chicken products.',
    couponCode: 'CHICKEN15',
    discountType: 'percentage',
    discountValue: '15%',
    validTill: '15 Jun, 2025',
    image: '/src/assets/images/offer_chicken_card_1790507696774.jpg',
    isActive: true,
  },
  {
    id: 'off_3',
    title: 'Free Delivery on First 3 Orders',
    description: 'Zero delivery fee for new Meat Ghar app customers.',
    couponCode: 'MEATFIRST',
    discountType: 'flat',
    discountValue: 'Free Delivery',
    validTill: '31 Dec, 2025',
    image: '/src/assets/images/meat_delivery_70_1790501379469.jpg',
    isActive: true,
  },
  {
    id: 'off_4',
    title: '20% Mega Weekend Seafood Bash',
    description: 'Special 20% discount on tiger prawns and pomfret.',
    couponCode: 'SEAFOOD20',
    discountType: 'percentage',
    discountValue: '20%',
    validTill: '10 May, 2025',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    isActive: false,
  },
];

export const INITIAL_SALES_OVERVIEW: AdminSalesPoint[] = [
  { day: '22', dateNum: 22, revenue: 4200 },
  { day: '23', dateNum: 23, revenue: 8500 },
  { day: '24', dateNum: 24, revenue: 5600 },
  { day: '25', dateNum: 25, revenue: 10400 },
  { day: '26', dateNum: 26, revenue: 13200 },
  { day: '27', dateNum: 27, revenue: 11800 },
  { day: '28', dateNum: 28, revenue: 16400 },
];

export const SALES_CHART_DATA = INITIAL_SALES_OVERVIEW;

export const INITIAL_SUPPORT_TICKETS: AdminSupportTicket[] = [
  {
    id: 'tick_101',
    ticketNumber: '#TICK-8021',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    orderNumber: '#ORD1024',
    subject: 'Rider is running 10 mins late on delivery',
    category: 'Delivery Delay',
    priority: 'High',
    status: 'Open',
    lastMessage: 'Sir, I have guests waiting for lunch. When will the rider arrive?',
    lastUpdated: '2 mins ago',
    unreadCount: 2,
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'Hello, my order #ORD1024 status is showing out for delivery for 40 mins now.',
        time: '10:35 AM',
      },
      {
        id: 'm2',
        sender: 'customer',
        text: 'Sir, I have guests waiting for lunch. When will the rider arrive?',
        time: '10:38 AM',
      },
    ],
  },
  {
    id: 'tick_102',
    ticketNumber: '#TICK-8020',
    customerName: 'Ayesha Khan',
    customerPhone: '+91 98123 45678',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    orderNumber: '#ORD1023',
    subject: 'Requesting extra ice packing for marinated chicken',
    category: 'Quality Issue',
    priority: 'Medium',
    status: 'In Progress',
    lastMessage: 'We have informed the packing station and ice pouches are added.',
    lastUpdated: '15 mins ago',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'Hi Meat Ghar team! Please ensure double vacuum chilled packing for Malai Tikka.',
        time: '09:50 AM',
      },
      {
        id: 'm2',
        sender: 'admin',
        text: 'We have informed the packing station and ice pouches are added.',
        time: '09:55 AM',
      },
    ],
  },
  {
    id: 'tick_103',
    ticketNumber: '#TICK-8019',
    customerName: 'Vikram Mehta',
    customerPhone: '+91 99887 76655',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    orderNumber: '#ORD1022',
    subject: 'Refund confirmation for cancelled item',
    category: 'Refund Request',
    priority: 'Medium',
    status: 'Resolved',
    lastMessage: 'Rs. 430 refunded to your original UPI payment method.',
    lastUpdated: '1 hour ago',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'Can you please check why my previous refund of Rs. 430 was delayed?',
        time: '08:30 AM',
      },
      {
        id: 'm2',
        sender: 'admin',
        text: 'Rs. 430 refunded to your original UPI payment method. Transaction ID: UPI-9988112.',
        time: '08:45 AM',
      },
    ],
  },
  {
    id: 'tick_104',
    ticketNumber: '#TICK-8018',
    customerName: 'Amit Trivedi',
    customerPhone: '+91 98450 12345',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    orderNumber: '#ORD1020',
    subject: 'Can I add eggs to my pending order?',
    category: 'General Query',
    priority: 'Low',
    status: 'Open',
    lastMessage: 'I forgot to add a pack of 30 eggs, can you include it?',
    lastUpdated: '35 mins ago',
    unreadCount: 1,
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'I forgot to add a pack of 30 eggs, can you include it in my order #ORD1020?',
        time: '11:20 AM',
      },
    ],
  },
];

export const INITIAL_BANNERS: AdminBanner[] = [
  {
    id: 'ban_1',
    title: '70 MINUTES',
    subtitle: 'OR FREE',
    tagline: 'Fresh meat delivered to your doorstep.',
    badgeText: 'Fresh & Safe',
    image: '/src/assets/images/hero_banner_meat_1790507616083.jpg',
    targetCategory: 'mutton',
    targetCategoryName: 'Mutton',
    backgroundColor: 'from-[#6e0513] via-[#8c0818] to-[#48020b]',
    buttonText: 'Order Now',
    isActive: true,
    orderIndex: 0,
  },
  {
    id: 'ban_2',
    title: 'FRESH CATCH',
    subtitle: 'SEA & RIVER FISH',
    tagline: 'Bengali cut Rohu, Surmai steaks & Pomfret cleaned fresh.',
    badgeText: 'Catch of Day',
    image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
    targetCategory: 'fish',
    targetCategoryName: 'Fish',
    backgroundColor: 'from-[#0e3b43] via-[#155e75] to-[#082f49]',
    buttonText: 'Explore Fish',
    isActive: true,
    orderIndex: 1,
  },
  {
    id: 'ban_3',
    title: 'JUICY CHICKEN',
    subtitle: 'FLAT ₹100 OFF',
    tagline: 'Farm-fresh curry cuts, drumsticks & tender breast fillets.',
    badgeText: 'Top Choice',
    image: '/src/assets/images/chicken_curry_cut_wide_1790508282856.jpg',
    targetCategory: 'chicken',
    targetCategoryName: 'Chicken',
    backgroundColor: 'from-[#7c2d12] via-[#9a3412] to-[#431407]',
    buttonText: 'Order Chicken',
    isActive: true,
    orderIndex: 2,
  },
  {
    id: 'ban_4',
    title: 'READY TO GRILL',
    subtitle: 'KEBABS & TIKKA',
    tagline: 'Marinated Malai Tikka & Seekh kebabs ready in 8 mins.',
    badgeText: 'Chef Special',
    image: '/src/assets/images/cat_ready_to_cook_1790507566251.jpg',
    targetCategory: 'ready-to-cook',
    targetCategoryName: 'Ready to Cook',
    backgroundColor: 'from-[#312e81] via-[#3730a3] to-[#1e1b4b]',
    buttonText: 'View Kebabs',
    isActive: true,
    orderIndex: 3,
  },
];

export const INITIAL_FLASH_DEALS: AdminFlashDeal[] = [
  {
    id: 'fd_1',
    title: 'Flash Deal - Fresh Rohu Fish Steak',
    productName: 'Fresh Rohu Fish Cut (Steak)',
    category: 'Fish',
    categoryId: 'fish',
    price: 260,
    originalPrice: 320,
    discountPercentage: '19% OFF',
    image: '/src/assets/images/rohu_fish_wide_1790508321588.jpg',
    stockLeft: 12,
    totalStock: 30,
    endsInMinutes: 120,
    unit: '1 KG',
    isActive: true,
  },
  {
    id: 'fd_2',
    title: 'Weekend Flash - Fresh Mutton Boneless',
    productName: 'Royal Mutton Boneless Cubes',
    category: 'Mutton',
    categoryId: 'mutton',
    price: 680,
    originalPrice: 780,
    discountPercentage: '13% OFF',
    image: '/src/assets/images/mutton_boneless_wide_1790508301717.jpg',
    stockLeft: 8,
    totalStock: 25,
    endsInMinutes: 90,
    unit: '1 KG',
    isActive: true,
  },
  {
    id: 'fd_3',
    title: 'Lightning Deal - Chicken Curry Cut',
    productName: 'Farm Fresh Chicken Curry Cut',
    category: 'Chicken',
    categoryId: 'chicken',
    price: 390,
    originalPrice: 460,
    discountPercentage: '15% OFF',
    image: '/src/assets/images/chicken_curry_cut_wide_1790508282856.jpg',
    stockLeft: 18,
    totalStock: 40,
    endsInMinutes: 150,
    unit: '1 KG',
    isActive: true,
  },
  {
    id: 'fd_4',
    title: 'Jumbo Prawns Flash Promo',
    productName: 'Fresh Sea Tiger Prawns (Cleaned)',
    category: 'Prawns & Seafood',
    categoryId: 'prawns',
    price: 690,
    originalPrice: 830,
    discountPercentage: '17% OFF',
    image: '/src/assets/images/cat_prawns_seafood_1790508815698.jpg',
    stockLeft: 6,
    totalStock: 20,
    endsInMinutes: 60,
    unit: '500G',
    isActive: true,
  },
];


